version: "3.8"

services:
  schedule-proxy:
    image: nginx:1.18.0-alpine
    container_name: schedule-proxy
    volumes:
      - "./public:/usr/src/app/public:ro"
      - "./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8088:80"
    depends_on:
      - schedule-api
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    networks:
      - schedule-dev-api-net

  schedule-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: schedule-api:dev
    container_name: schedule-api
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - schedule-dev-api-net

  schedule-database:
    image: mysql:8
    container_name: schedule-database
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/provision:/docker-entrypoint-initdb.d"
      - "./db/files/over.cnf:/etc/mysql/conf.d/over.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=schedule
      - MYSQL_DATABASE=schedule
      - MYSQL_USER=schedule
      - MYSQL_PASSWORD=schedule
    ports:
      - "6667:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    networks:
      - schedule-dev-api-net

networks:
  schedule-dev-api-net:
    name: schedule-dev-api-net