apiVersion: v1
kind: ConfigMap
metadata:
  name: default-configmap
data:
  default.conf: |
    upstream api-web{
        server localhost:9000;
    }
    server {
        listen 80 default;
        client_max_body_size 108M;
        access_log /var/log/nginx/application.access.log;
        root /usr/src/app/public;
        index index.php;
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
                                                    return 444;
                                                    }
        ##Configuraciones root
        location / {
            index index.php;
            try_files $uri $uri/ /index.php;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;
            if (-f $request_filename) {
                expires 30d;
                break;
            }
            if (!-e $request_filename) {
                rewrite ^(.+)$ /index.php last;
            }
        }
        location ~ \.php$ {
            fastcgi_pass api-web;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
            fastcgi_read_timeout 900;
        }
        ##Configuraciones location extras
        location /css {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/css/(.*) /assets/css/$1 break;
        }
        location /js {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/js/(.*) /assets/js/$1 break;
        }
        location /views {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/views/(.*) /assets/views/$1 break;
        }
        location /font {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/font/(.*) /assets/font/$1 break;
        }
        location /fonts {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/fonts/(.*) /assets/fonts/$1 break;
        }
        location /images {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/images/(.*) /assets/images/$1 break;
        }
        location /imagenes {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/imagenes/(.*) /assets/imagenes/$1 break;
        }
       location /media {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/media/(.*) /assets/media/$1 break;
        }
       location /storage/uploads/~*\.(?:ico|css|js|gif|jpe?g|png)$ {
            expires 30d;
            add_header Pragma public;
            add_header Cache-Control "public";
            try_files $uri =404;
        }
       location /downloads {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/downloads/(.*) /assets/downloads/$1 break;
        }
        location /favicon {
            expires 30d;
            access_log off;
            add_header Cache-Control "public";
            rewrite "^/(.*)\.[0-9a-f]{32}(\.(.*))$" /$1$2;
            rewrite ^/favicon\.ico$ /assets/favicon.ico break;
        }
    }
    types {
        font/ttf                             ttf;
    }